services:
  mongo:
    container_name: mongo-clean-node-api
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    container_name: app-clean-node-api
    build: .
    restart: always
    image: clean-node-api/1.0.0
    ports:
      - "3000:3000"
      - "9222:9222"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo-clean-node-api:27017
    command: npm run debug
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    links:
      - mongo
