services:
  mongo:
    container_name: mongo-clean-node-api
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    container_name: app-clean-node-api
    build: .
    command: npm run watch
    restart: always
    ports:
      - "3000:3000"
      - "9222:9222"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo-clean-node-api:27017
    links:
      - mongo
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/clean-node-api/src
        - action: rebuild
          path: ./package.json
